# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mical = {
    pname = "mical";
    version = "v0.0.2";
    src = fetchFromGitHub {
      owner = "mical-lang";
      repo = "mical";
      rev = "v0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-16NSGJTBbKEhWymfL2UaBfkRZzJ7yn+XT45lSHAhw88=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-16NSGJTBbKEhWymfL2UaBfkRZzJ7yn+XT45lSHAhw88=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  pleckjp-font = {
    pname = "pleckjp-font";
    version = "v2.1.2";
    src = fetchurl {
      url = "https://github.com/ryota2357/PleckJP/releases/download/v2.1.2/PleckJP_v2.1.2.zip";
      sha256 = "sha256-h7iW/arXNQZuW+9OpKdAWF9FtjSyi9/DLIuyuE1ckCY=";
    };
  };
  vm_stat2 = {
    pname = "vm_stat2";
    version = "c16f3891269735d882330113cd0a43254706e778";
    src = fetchFromGitHub {
      owner = "ryota2357";
      repo = "vm_stat2";
      rev = "c16f3891269735d882330113cd0a43254706e778";
      fetchSubmodules = false;
      sha256 = "sha256-3qYLoThayhROhOdATyJw7UM+9wfU4kXS+Fm4rTyexIg=";
    };
    date = "2026-04-12";
  };
}
