# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vm_stat2 = {
    pname = "vm_stat2";
    version = "83349699f0773be1d18daed358f7d50b5fefccda";
    src = fetchFromGitHub {
      owner = "ryota2357";
      repo = "vm_stat2";
      rev = "83349699f0773be1d18daed358f7d50b5fefccda";
      fetchSubmodules = false;
      sha256 = "sha256-UGJAghgqbuN3HIYrE+/ImjMwErrE6lYKeXhVk8nc+ZE=";
    };
    date = "2026-01-12";
  };
}
